Fix specs
- By always allowing Setting to receive api_token and returning a valid
  token. The tests were passing locally since I had a token in my env
whereas the runner did not have one. Calling secure_compare with nil as
a param throws an error NoMethodError (undefined method `bytesize' for nil:NilClass)