Upgrade signal-cli-rest-api to v0.97 (#2157)
We started receiving:

```
org.signal.libsignal.protocol.InvalidMessageException: protobuf encoding was invalid
```

so we upgraded since it had been a while and the errors went away for
now